### PR TITLE
Added Truths on some and Humor on others

### PR DESCRIPTION
**Pull request by MathManiac0**
*mainly regarding Issue #18*
> The biggest flaw in the best tools are the misinformation about them.

With the above quote in mind, I tried to give disclaimers and more information on the website. This can help:
- **More users will trust Linux better.** They might see linux to be "Too good to be true", and when something contrary to what they heared happen, they'll just install Windows again...
- **It will remove unnecessary expectations for Linux.** Similar to above, except users might install Linux with full trust. They won't bother with Antivirus, 'cause hey, Linux is secure! They start browsing on the internet, and gets Malware, Spyware, etc. This will completely shatter their trust.
- **Adds reliability to this website.** If this website gives more truth and less misinformation about Linux, then more people will follow this website's advice!

Thank you very much for reviewing my pull request, and tell me if you have any reccomendations!

### CODE REVIEW

**Comment by lmanul** [comment]
"An important thing to note is that some files can get defragmented, but 
<em>Only if you have a small amount memory left!</em> If you use a lot of
memory, or you create and delete files often (such as running a large
server), you might need to defragment once in a blue moon, but for the
average guy, you shouldn't need to defragment at all.</p>"

----

"Some files can get defragmeneted" -- ?
"Only" -- capital O in the middle of a sentence?
"If you use a lot of memory, or you create and delete files often (such as running a large server)" -- this syntax doesn't seem to really work, does it?

**Comment by MathManiac0** [comment]
I can fix it on Saturday.

**Comment by MathManiac0** [comment]
@lmanul The paragraph should look better now:
>An important thing to note is that files can get somewhat defragmented, but 
*only if you have a small amount memory left!* If you use a lot of
memory, or you create and delete files often - such as running a large
server - you might need to defragment once in a blue moon. However, for the
average computer user, you shouldn't need to defragment at all.

**Comment by aaronfranke** [comment]
"An important thing to note is that files can get somewhat defragmented"

You mean fragmented?

**Comment by MathManiac0** [comment]
@aaronfranke Thanks, I missed that!

**Comment by MathManiac0** [comment]
@lmanul Can you explain why you closed this? I really want to help improve the website.

**Comment by lmanul** [comment]
I closed this because the patch didn't really look good to me. It bundled many things in the same pull request, had an average of one typo per line of text and felt kind of long winded to me...

**Comment by MathManiac0** [comment]
All right, thanks! I'll see if I can approve!

**Comment by lmanul** [comment]
You probably meant improve.

**Comment by MathManiac0** [comment]
Can't seem to disable autocorrect on my phone

**Pull request closed without merging**
